# Site settings
title: Gyj1109's blog
email: gyj1109@126.com
description: "My blog"
baseurl: ""
url: "http://gyj1109.github.io"
permalink: /:year:month/:title
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: Asia/Shanghai
# future: true

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
twitter:    gyj1109
# weibo:    gyj1109
github:     gyj1109
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: gyj1109


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
